<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410084519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (matricule VARCHAR(10) NOT NULL, aianalyser_id INT DEFAULT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_880E0D766602877 ON admin (aianalyser_id)');
        $this->addSql('CREATE TABLE aianalyser (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, modele_analyse VARCHAR(255) NOT NULL, modele_recommendation VARCHAR(255) NOT NULL, seuil_anomalie NUMERIC(5, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE budget (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant_max INT NOT NULL, categorie_budget VARCHAR(255) NOT NULL, client_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_73F2F77B19EB6921 ON budget (client_id)');
        $this->addSql('CREATE TABLE client (num_compte VARCHAR(20) NOT NULL, cin VARCHAR(12) NOT NULL, activite VARCHAR(255) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE compte (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, solde INT NOT NULL, type_compte VARCHAR(255) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFF6526019EB6921 ON compte (client_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message VARCHAR(255) NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, a_ianalyser_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA34E298F2 ON notification (a_ianalyser_id)');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_transaction VARCHAR(255) NOT NULL, montant_transaction INT NOT NULL, date_transaction TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, categorie_transaction VARCHAR(255) NOT NULL, compte_id INT DEFAULT NULL, a_ianalyser_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1F2C56620 ON transaction (compte_id)');
        $this->addSql('CREATE INDEX IDX_723705D134E298F2 ON transaction (a_ianalyser_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_utilisateur VARCHAR(255) NOT NULL, prenom_utilisateur VARCHAR(255) NOT NULL, mot_de_passe_utilisateur TEXT NOT NULL, email_utilisateur VARCHAR(255) NOT NULL, telephone_utilisateur VARCHAR(255) NOT NULL, adresse_utilisateur VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D766602877 FOREIGN KEY (aianalyser_id) REFERENCES aianalyser (id)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76BF396750 FOREIGN KEY (id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE budget ADD CONSTRAINT FK_73F2F77B19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455BF396750 FOREIGN KEY (id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE compte ADD CONSTRAINT FK_CFF6526019EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA34E298F2 FOREIGN KEY (a_ianalyser_id) REFERENCES aianalyser (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1F2C56620 FOREIGN KEY (compte_id) REFERENCES compte (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D134E298F2 FOREIGN KEY (a_ianalyser_id) REFERENCES aianalyser (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin DROP CONSTRAINT FK_880E0D766602877');
        $this->addSql('ALTER TABLE admin DROP CONSTRAINT FK_880E0D76BF396750');
        $this->addSql('ALTER TABLE budget DROP CONSTRAINT FK_73F2F77B19EB6921');
        $this->addSql('ALTER TABLE client DROP CONSTRAINT FK_C7440455BF396750');
        $this->addSql('ALTER TABLE compte DROP CONSTRAINT FK_CFF6526019EB6921');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA34E298F2');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1F2C56620');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D134E298F2');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE aianalyser');
        $this->addSql('DROP TABLE budget');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE compte');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
